### ISSUE TITLE
LogViewer not working in specific circumstances

### ISSUE THREAD

**Issue by LJBD** [tango-controls-migration-tests/TangoTickets#2]
Hello!

I've come across the following problem today on my Windows machine: I've started Jive and changed the Tango Host using menu Edit->Change Tango Host option. Afterwards, I've started LogViewer for the new host, but I haven't been able to subscribe to any logs. LogViewer has shown the following error:
```
=== ERROR ==========================================
Severity: ERROR
Origin: DeviceImpl::add_logging_target
Description: Could not connect to log consumer tmp/log/lukaszdudeksolaris@102
Reason: API_ConnectionFailed
Severity: PANIC
Origin: Connection.command_inout()
Description: Cannot execute command AddLoggingTarget on dserver/VacuumParameters/R1-ALL-VAC
Reason: TangoApi_CANNOT_EXECUTE_COMMAND

====================================================
```
It turned out that the LogConsumer device with the name mentioned in the exception's description has been registered on the wrong Tango Host - on the one that was saved in the system environmental variable, not the one I gave to Jive by hand.

My guess is that starting LogViewer triggers starting LogConsumer - if that's the case it should also get the Tango Host for which LogViewer has been started.

This behaviour might be a Windows-only problem, I haven't performed any tests on Linux yet.

**Comment by bourtemb** [comment]
Hi,
How did you start the LogViewer?
As far as I know, the LogViewer is an application which is independent from jive.
I guess it is connecting to the TANGO_HOST defined by your system environment variable only.
If you change the TANGO_HOST on jive, it won't change your TANGO_HOST system environment variable.
As far as I understood, there has been a request to improve the LogViewer in order to support multiple TANGO_HOSTs.
I am no LogViewer expert but I guess in your case, you would need to update the TANGO_HOST system environment variable before starting your LogViewer to get what you expects...
LogViewer experts could comment of course ;-)...
Cheers,
Reynald

**Comment by LJBD** [comment]
Hello!

Thank you for a quick reply!
I'm aware that LogViewer is a standalone application, but it can be launched from a context menu in Jive and that's how I've started it. If it's launched that way, it gets Jive's Tango Host - even when you've used "Change Tango Host" option in Jive. I'm aware of the fact that changing TANGO_HOST environment variable will make it work in all cases. I'm just pinpointing an issue that it outside "normal" scope of usage.

The request concerns a very specific launch case - I'd summarise it as: in this case LogViewer can't be used because LogConsumer devices have been launched with wrong Tango Host. And that's an issue that could be addressed.

I've checked and it behaves the same way on Linux hosts.

Best regards,
Łukasz

**Comment by bourtemb** [comment]
Hi Łukasz,

Thanks for the details.
So it looks like this problem is mainly due to a problem in the LogViewer application itself when passing as parameter the fully qualified device name from a device having a TANGO_HOST different than the one declared in the TANGO_HOST environment variable.
So it looks like it is a LogViewer issue, not a jive issue.
Could you please create an issue on LogViewer GitHub repository?
Many thanks.
Reynald

**Comment by LJBD** [comment]
Hello, Reynald!

Of course, I'll create an issue.
I wasn't sure if that's a problem with LogViewer or some backend in log4tango and that's why I chose to open an issue here.
Thanks a lot for your help!

Best regards,
Łukasz
