### ISSUE TITLE
Set Value is 0 when restarting DS

### ISSUE THREAD

**Issue by mrosanes** [tango-controls-migration-tests/TangoTickets#25]
Dear Tango,

I have a question about the Set Value when restarting a DS.

We have observed that when we restart a Device Server, the Set Value of a numeric attribute is initialized to 0.0
This should be the case? 

Maybe, should it be better to initialize it with "Not Specified"?

Thanks in advance,

**Comment by bourtemb** [comment]
> We have observed that when we restart a Device Server, the Set Value of a numeric attribute is initialized to 0.0
> This should be the case?

Indeed, it is initialized like that. This is the current expected behaviour.

I think this is not a bad idea to notify the client that the set value has not yet been specified. This would indeed be cleaner, for any attribute type, even DevString (which is currently initialised to "Not initialised").
To do this, we would need to change the protocol to find a way to provide this information to the client when it reads the attribute (a new flag in DeviceAttribute object? This info would need to be transferred on the network too...).
All the client libraries in the different languages (C++, Python, Java, REST API...) would need to be updated to take this flag into account. Frameworks like ATK, Taurus or Cumbia would need to adapt their widgets to display this information too.
For the moment, the client gets the set value together with the read value, in an array of the same type of the attribute type. You are probably programming in python with PyTango...?
PyTango is using the C++ library underneath and in C++, you cannot set a numerical variable to a string value.

I think we should keep this idea in mind for the definition of what we want for Tango V10.
@lorenzopivetta , @andygotz, could you try to take this into account when writing the specs for Tango V10 if we agree we want this feature of course?

**Comment by mrosanes** [comment]
Many thanks for the fast answer, Reynald.
I'll also ask to my colleagues if they would find it a good idea (or not) to have this feature in future versions of Tango.

**Comment by mrosanes** [comment]
Hi Tango community,

At ALBA @sergirubio has done some more tests regarding the set values after restarting a DS:

 - For numeric scalar values, the default set_value is 0
 - For spectrum/string, the default set_value is 'Not initialized'
 - For booleans, the default set_value is "True" 

Our position at ALBA is that in v10 this should be solved by applying the spectrum/string approach to everything: i.e: using 'Not initialized'

**Comment by bourtemb** [comment]
You might be able to patch PyTango to do that but again, this is not possible for C++ or Java bindings.
You cannot assign a string to a integer value in C++ or Java.

**Comment by mrosanes** [comment]
Sorry, I amend my last comment. The idea would not be to set everything to 'Not initialized' given that this is not possible in C++/Java.

We only think that this issue should be kept in mind in the specifications of Tango v10, if possible, and if the Tango community agrees on it. Finding a way to provide this information (e.g. using a flag, as proposed).

**Comment by piogor** [comment]
Hi, what about signaling this with the attr_quality?

Br. Piotr

**Comment by bourtemb** [comment]
attr_quality is usually linked to the attribute read value.
What would be the attr_quality if the read value is in alarm (Read value above alarm threshold) and the set point not initialized.
You would get a bunch of new attribute qualities like:
ALARM_AND_SET_POINT_NOT_INITIALIZED
MOVING_AND_SET_POINT_NOT_INITIALIZED
.... ?
I think a new flag could be used for that... Unless we associate different attr_qualities for read values and set values. 
So a RW attribute would have 2 associated attribute qualities: one for the read value and one for the set value?

**Comment by lorenzopivetta** [comment]
Hi all,
some more thoughts about this...
1) in general, the behavior of the device with respect of the set-point is not always the same. Some equipment, or some subsystem, or some specialist, sometimes specifies a default initialization value for device startup, regardless of the state (e.g. first startup or device restart)
2) if the set-point is really relevant, that may conveniently become a memorized attribute
3) if the device design does not require to restore the set-point at startup, the RDS alarm should also help understanding that there's something missing... provided the appropriate thresholds have been specified.
Summarizing, I'm not sure there is a real need for an additional mechanism...
