### ISSUE TITLE
segfault on read_attribute, when pushing event after attr.set_value_date_quality

### ISSUE THREAD

**Issue by sergirubio** [tango-controls-migration-tests/TangoTickets#29]
Tested with latest pytango/tango (9.3.4)

Within a read_Attribute method in a device server; if push_change_event(attr,..) is called after attr.set_value_date_quality(...) ... a segmentation fault occurs in the device server.

def read_...(self):
  attr.set_value_date_quality(value,t,quality)
  self.push_change_event(name,value,t,quality)

Just reversing the two lines, the segfault disappears (first push, then set_value)

**Comment by mliszcz** [comment]
This issue was reported long ago here: https://github.com/tango-controls/cppTango/issues/443
Recently I started to work on it in https://github.com/tango-controls/cppTango/pull/698.

Unfortunately, it is not possible to fix this without breaking API (because push_event releases the buffer which set_value is expected to fill). In above mentioned PR you will get an API_AttrValueNotSet exception instead of a crash.
