### ISSUE TITLE
Gitlab Migration: Please log into GL with your GH account ASAP

### ISSUE THREAD

**Issue by t-b** [tango-controls-migration-tests/TangoTickets#53]
Dear TangoTickets participant (via commits, comments on issue or pull requests, issue creator),

If you have contributed in any way (commit, issue or Pull Request creation or comment) to TangoTickets, please log into Gitlab.com using your Github account ASAP.
See tango-controls/TangoTickets#47 for details.

Please click on the following link and add your github account name to this framapad when you've already done the login to Gitlab.com using your Github account:
https://mensuel.framapad.org/p/migration_ready_2548763689

For convenience, here is the list of contributors we could already find:
- [ ] @GrigoryPrutskov
- [ ] @LJBD
- [x] @Pascal-Verdier
- [ ] @alainbuteau 
- [ ] @chedburgh 
- [x] @cpascual 
- [x] @faranguiss-poncet
- [ ] @ra1u
- [x] @sblanchet
- [x] @sdebionne
- [ ] @stufisher
- [x] @teresanunez
- [ ] @weibu

Please note that login on gitlab.com using your Github account is safe and doesn't give your Github password to Gitlab.

Thanks for your cooperation.

**Comment by teresanunez** [comment]
Dear Thomas, I have done the login to gitlab using the github authentification.

**Comment by cpascual** [comment]
Hint: in order to avoid spamming, and since many of the contributors will be shared among the tango projects, we can filter the list of people to be mentioned using the [framapad list](https://mensuel.framapad.org/p/migration_ready_2548763689). 
This can be done automatically by the [`getparticipants.py` script](https://github.com/tango-controls/gitlab-migration-tools/blob/master/get_participants.py) by adding the names from the pad to [the `excluded` file](https://github.com/tango-controls/gitlab-migration-tools/blob/master/excluded)
